routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
 // Mosque Routes
Route::resource('mosque', 'MosqueController');

app/Mosque.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Mosque extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Mosque;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $mosques = Mosque::all();
        return view('home', ['mosques' => $mosques]);
    }
}

app/Http/Controllers/MosqueController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Mosque;

class MosqueController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $mosques = Mosque::orderBy('id', 'desc')->get();
        return view('home', ['mosques' => $mosques]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('mosque_add_from');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $mosque = new Mosque;

        $mosque->li_type = $request->li_type;
        $mosque->mos_li_name = $request->mos_li_name;
        $mosque->division = $request->division;
        $mosque->district = $request->district;
        $mosque->upazilla = $request->upazilla;
        $mosque->union = $request->union;
        $mosque->village = $request->village;
        $mosque->li_o_year = $request->li_o_year;
        $mosque->i_f_p_bn = $request->i_f_p_bn;
        $mosque->b_p_p_bn = $request->b_p_p_bn;
        $mosque->i_k_p = $request->i_k_p;
        $mosque->n_o_p = $request->n_o_p;
        $mosque->amlamir_date = $request->amlamir_d .'-'. $request->amlamir_m .'-'. $request->amlamir_y;
        $mosque->total_e_p_no = $request->total_e_p_no;
        $mosque->sineboard_is = $request->sineboard_is;
        $mosque->ms_e_p = $request->ms_e_p;
        $mosque->month_avg_p = $request->month_avg_p;
        $mosque->p_no_l = $request->p_no_l;
        $mosque->monthly_female_p = $request->monthly_female_p;

        $mosque->ms_activities = $request->ms_activities_b_s .'-'. $request->ms_activities_s_o .'-'.$request->ms_activities_o_m .'-'.$request->ms_activitie_s_s;

        $mosque->l_v_date = $request->last_visit_date .'-'. $request->last_visit_month .'-'. $request->last_visit_year; 

        $mosque->l_v_p_name = $request->lasl_vstd_person_name;
        $mosque->l_v_p_address = $request->lasl_vstd_person_address;

        $mosque->save();
        return redirect()->back()->with('success', 'Success! Mosque Library information successfully saved.');

// array:31 [▼
//   "_token" => "ocsnhm9S0JVpn06nlc4APJ8pgoyIYfp8jTlwgdXR"
//   "li_type" => "মডেল মসজিদ পাঠাগার"
//   "mos_li_name" => "dsafas"
//   "division" => "dsaf"
//   "district" => "asdfadf"
//   "upazilla" => "sadfas"
//   "union" => "sdafsd"
//   "village" => "dsafas"
//   "li_o_year" => "4353"
//   "i_f_p_bn" => "3453"
//   "b_p_p_bn" => "345"
//   "i_k_p" => "345"
//   "n_o_p" => "345"
//   "amlamir_d" => "45"
//   "amlamir_m" => "345"
//   "amlamir_y" => "345"
//   "total_e_p_no" => null
//   "sineboard_is" => "হ্যাঁ"
//   "ms_e_p" => "34"
//   "month_avg_p" => "345"
//   "p_no_l" => "তরুণ/তরুণী"
//   "monthly_female_p" => "345"
//   "ms_activities_b_s" => "বয়স্ক শিক্ষা"
//   "ms_activities_s_o" => "সাংস্কৃতিক  অনুষ্ঠান"
//   "ms_activities_o_m" => "ওয়াজ মাহফিল"
//   "ms_activitie_s_s" => "সমসাময়িক সামাজিক ইস্যুভিত্তিক আলোচনা"
//   "last_visit_date" => "454"
//   "last_visit_month" => "454"
//   "last_visit_year" => "454"
//   "lasl_vstd_person_name" => "asdfas"
//   "lasl_vstd_person_address" => "saf"
// ]
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/home.blade.php
@extends('layouts.app')
@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <span  class="navbar-brand text-bold">মসজিদ পাঠাগার সম্প্রসারণ ও শক্তিশালী প্রকল্প</span>
                    <a href="{{ route('mosque.create') }}" class="btn btn-sm btn-success" style="float: right;"> + মসজিদ পাঠাগার ডাটাবেজ ফরম</a>
                </div>
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <div style="overflow: scroll; height:100%" class="table-wrapper-scroll-y my-custom-scrollbar"> 
                        <table id="dataTable" class="table table-striped table-bordered table-sm " cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>নাম</th>
                                    <th>ধরন</th>
                                    <th>বিভাগ</th>
                                    <th>জেলা</th>
                                    <th>উপজেলা/পৌর</th>
                                    <th>ইউনিয়ন</th>
                                    <th>গ্রাম-রোড</th>
                                    <th>প্রতিষ্ঠা</th>
                                    <th>পুস্তক সংখ্যা (ইফা)</th>
                                    <th>পুস্তক সংখ্যা (বাহির)</th>
                                    <th>আলমারীর সংখ্যা</th>
                                    <th>আলমারী প্রদানের তারিখ</th>
                                    <th>পরিদর্শন সংখ্যা</th>
                                    <th>সাইনবোর্ড</th>
                                    <th>গড় পাঠক (দৈনিক)</th>
                                    <th>গড় পাঠক (মাসিক)</th>
                                    <th>বেশীরভাগ পাঠকের বয়স</th>
                                    <th style="font-size:11px;">গড় মহিলা পাঠক (মাসিক)</th>
                                    <th>পরিচালিত কার্যক্রম</th>
                                    <th>সর্বশেষ পরিদর্শন</th>
                                    <th>পরিদর্শনকারীর নাম</th>
                                    <th>পরিদর্শনকারীর পদবী ও ঠিকানা</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($mosques as $key=>$mosque)
                                    <tr>
                                      <td>{{ ++$key }}</td>
                                      <td style="font-size:10px;">{{ $mosque->li_type }}</td>
                                      <td style="font-size:10px;">{{ $mosque->mos_li_name }}</td>
                                      <td>{{ $mosque->division }}</td>
                                      <td>{{ $mosque->district }}</td>
                                      <td>{{ $mosque->upazilla }}</td>
                                      <td>{{ $mosque->union }}</td>
                                      <td style="font-size:9px;">{{ $mosque->village }}</td>
                                      <td>{{ $mosque->li_o_year }}</td>
                                      <td>{{ $mosque->i_f_p_bn }}</td>
                                      <td>{{ $mosque->b_p_p_bn }}</td>
                                      <td style="font-size:9px;"> ইফা কর্তৃক {{ $mosque->i_k_p }} টি & নিজন্ব উদ্যোগে {{ $mosque->n_o_p }} টি</td>
                                      <td>{{ $mosque->amlamir_date }}</td>
                                      <td>{{ $mosque->total_e_p_no }}</td>
                                      <td>{{ $mosque->sineboard_is }}</td>
                                      <td>{{ $mosque->ms_e_p }}</td>
                                      <td>{{ $mosque->month_avg_p }}</td>
                                      <td>{{ $mosque->p_no_l }}</td>
                                      <td>{{ $mosque->monthly_female_p }}</td>
                                      <td style="font-size:9px;">{{ $mosque->ms_activities }}</td>
                                      <td>{{ $mosque->l_v_date }}</td>
                                      <td>{{ $mosque->l_v_p_name }}</td>
                                      <td style="font-size:9px;">{{ $mosque->l_v_p_address }}</td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready( function () {
        $('#dataTable').DataTable();
    });
</script>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
    <script type="text/javascript" defer charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>

    <!-- <script src="{{ asset('js/jquery.min.js') }}"></script>
    <link rel="stylesheet" type="text/css" href="{{ asset('css/jquery.dataTables.css') }}">
    <script type="text/javascript" defer charset="utf8" src="{{ asset('js/jquery.dataTables.js') }}"></script> -->



    <!-- Styles -->
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/home') }}">
                    <img src="{{ url('images/logo.png') }}" width="100">
                </a>
                <a class="navbar-brand" href="{{ url('/home') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>
        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>